import { createPagesFunctionHandler } from '@react-router/cloudflare';

import * as build from "../build/server";

// @ts-ignore - the server build file is generated by `remix vite:build`
export const onRequest = createPagesFunctionHandler({ build });
